### ISSUE TITLE
IDA 6.3 cant load the BinNavi Plugin

### ISSUE THREAD

**Issue by reknerxam** [google/binnavi#6]
Exporting from IDA to BinNavi fails silently from within BinNavi when using IDA 6.3.

When opening IDA up I see the following error on the Output Console:

> LoadLibrary(C:\Program Files (x86)\IDA 6.3\plugins\zynamics_binexport_8.plw) error: The specified procedure could not be found.
C:\Program Files (x86)\IDA 6.3\plugins\zynamics_binexport_8.plw: can't load file

After a bit of digging, it seems IDA 6.3 (Via IDA.WLL) doesn't export the following imports required by the plugin:

```
get_ea_name
get_member_name2
get_tinfo2
guess_tinfo2
copy_tinfo_t
clear_tinfo_t
get_tinfo_size
get_tinfo_property
print_tinfo
get_member_tinfo2
netnode_get_name
```
Can older versions of the BinNavi exporter plugin be released for those of us who do not have a current IDA subscription and are left on an older version?

**Comment by cblichmann** [comment]
Back at zynamics, our stance on this was that we would support the two most recent versions of IDA Pro (currently 6.7 and 6.8). However, since our team has shifted its focus a bit, we don't have the time to support older versions properly. So for now, we're only supporting the most recent version (6.8). When 6.9 is released, we're back at two versions.
We're currently looking into making the code of the plugins available as well, but this will take a while, so don't hold your breath, sorry.

**Comment by reknerxam** [comment]
Fair enough, I can understand how this is not feasible. Thanks.

**Comment by Manouchehri** [comment]
What was the last BinNavi release that worked with IDA 6.3?

**Comment by cblichmann** [comment]
IIRC, the 5.x series should still support it.

**Comment by Manouchehri** [comment]
@reknerxam Now that BinExport is released, you might find it easier to get this working.
